// User
export const GET_USER_IS_PENDING = 'GET_USER_IS_PENDING';
export const GET_USER_WAS_SUCCESSFUL = 'GET_USER_WAS_SUCCESSFUL';
export const GET_USER_HAD_ERROR = 'GET_USER_HAD_ERROR';

export const GET_ORGS_IS_PENDING = 'GET_ORGS_IS_PENDING';
export const GET_ORGS_WAS_SUCCESSFUL = 'GET_ORGS_WAS_SUCCESSFUL';
export const GET_ORGS_HAD_ERROR = 'GET_ORGS_HAD_ERROR';

// Auth User
export const GET_AUTH_USER_IS_PENDING = 'GET_AUTH_USER_IS_PENDING';
export const GET_AUTH_USER_WAS_SUCCESSFUL = 'GET_AUTH_USER_WAS_SUCCESSFUL';
export const GET_AUTH_USER_HAD_ERROR = 'GET_AUTH_USER_HAD_ERROR';

export const GET_AUTH_ORGS_IS_PENDING = 'GET_AUTH_ORGS_IS_PENDING';
export const GET_AUTH_ORGS_WAS_SUCCESSFUL = 'GET_AUTH_ORGS_WAS_SUCCESSFUL';
export const GET_AUTH_ORGS_HAD_ERROR = 'GET_AUTH_ORGS_HAD_ERROR';

// User Events
export const GET_USER_EVENTS_IS_PENDING = 'GET_USER_EVENTS_IS_PENDING';
export const GET_USER_EVENTS_WAS_SUCCESSFUL = 'GET_USER_EVENTS_WAS_SUCCESSFUL';
export const GET_USER_EVENTS_HAD_ERROR = 'GET_USER_EVENTS_HAD_ERROR';
export const GET_MORE_USER_EVENTS = 'GET_MORE_USER_EVENTS';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Repository
export const SELECT_REPOSITORY = 'SELECT_REPOSITORY';

export const GET_REPOSITORY_IS_PENDING = 'GET_REPOSITORY_IS_PENDING';
export const GET_REPOSITORY_WAS_SUCCESSFUL = 'GET_REPOSITORY_WAS_SUCCESSFUL';
export const GET_REPOSITORY_HAD_ERROR = 'GET_REPOSITORY_HAD_ERROR';

export const GET_REPOSITORY_CONTRIBUTORS_IS_PENDING = 'GET_REPOSITORY_CONTRIBUTORS_IS_PENDING';
export const GET_REPOSITORY_CONTRIBUTORS_WAS_SUCCESSFUL = 'GET_REPOSITORY_CONTRIBUTORS_WAS_SUCCESSFUL';
export const GET_REPOSITORY_CONTRIBUTORS_HAD_ERROR = 'GET_REPOSITORY_CONTRIBUTORS_HAD_ERROR';

export const GET_REPOSITORY_TOP_CONTENTS_IS_PENDING = 'GET_REPOSITORY_TOP_CONTENTS_IS_PENDING';
export const GET_REPOSITORY_TOP_CONTENTS_WAS_SUCCESSFUL = 'GET_REPOSITORY_TOP_CONTENTS_WAS_SUCCESSFUL';
export const GET_REPOSITORY_TOP_CONTENTS_HAD_ERROR = 'GET_REPOSITORY_TOP_CONTENTS_HAD_ERROR';

export const GET_REPOSITORY_ISSUES_IS_PENDING = 'GET_REPOSITORY_ISSUES_IS_PENDING';
export const GET_REPOSITORY_ISSUES_WAS_SUCCESSFUL = 'GET_REPOSITORY_ISSUES_WAS_SUCCESSFUL';
export const GET_REPOSITORY_ISSUES_HAD_ERROR = 'GET_REPOSITORY_ISSUES_HAD_ERROR';

export const GET_REPOSITORY_README_IS_PENDING = 'GET_REPOSITORY_README_IS_PENDING';
export const GET_REPOSITORY_README_WAS_SUCCESSFUL = 'GET_REPOSITORY_README_WAS_SUCCESSFUL';
export const GET_REPOSITORY_README_HAD_ERROR = 'GET_REPOSITORY_README_HAD_ERROR';
