// Auth User
export const GET_AUTH_USER_IS_PENDING = 'GET_AUTH_USER_IS_PENDING';
export const GET_AUTH_USER_WAS_SUCCESSFUL = 'GET_AUTH_USER_WAS_SUCCESSFUL';
export const GET_AUTH_USER_HAD_ERROR = 'GET_AUTH_USER_HAD_ERROR';

export const GET_AUTH_ORGS_IS_PENDING = 'GET_AUTH_ORGS_IS_PENDING';
export const GET_AUTH_ORGS_WAS_SUCCESSFUL = 'GET_AUTH_ORGS_WAS_SUCCESSFUL';
export const GET_AUTH_ORGS_HAD_ERROR = 'GET_AUTH_ORGS_HAD_ERROR';

// User
export const GET_USER_IS_PENDING = 'GET_USER_IS_PENDING';
export const GET_USER_WAS_SUCCESSFUL = 'GET_USER_WAS_SUCCESSFUL';
export const GET_USER_HAD_ERROR = 'GET_USER_HAD_ERROR';

export const GET_ORGS_IS_PENDING = 'GET_ORGS_IS_PENDING';
export const GET_ORGS_WAS_SUCCESSFUL = 'GET_ORGS_WAS_SUCCESSFUL';
export const GET_ORGS_HAD_ERROR = 'GET_ORGS_HAD_ERROR';

// User Info List
export const GET_USER_INFO_LIST_IS_PENDING = 'GET_USER_INFO_LIST_IS_PENDING';
export const GET_USER_INFO_LIST_WAS_SUCCESSFUL = 'GET_USER_INFO_LIST_WAS_SUCCESSFUL';
export const GET_USER_INFO_LIST_HAD_ERROR = 'GET_USER_INFO_LIST_HAD_ERROR';

// Organization
export const GET_ORG_IS_PENDING = 'GET_ORG_IS_PENDING';
export const GET_ORG_WAS_SUCCESSFUL = 'GET_ORG_WAS_SUCCESSFUL';
export const GET_ORG_HAD_ERROR = 'GET_ORG_HAD_ERROR';

export const GET_ORG_REPOS_IS_PENDING = 'GET_ORG_REPOS_IS_PENDING';
export const GET_ORG_REPOS_WAS_SUCCESSFUL = 'GET_ORG_REPOS_WAS_SUCCESSFUL';
export const GET_ORG_REPOS_HAD_ERROR = 'GET_ORG_REPOS_HAD_ERROR';

export const GET_ORG_MEMBERS_IS_PENDING = 'GET_ORG_MEMBERS_IS_PENDING';
export const GET_ORG_MEMBERS_WAS_SUCCESSFUL = 'GET_ORG_MEMBERS_WAS_SUCCESSFUL';
export const GET_ORG_MEMBERS_HAD_ERROR = 'GET_ORG_MEMBERS_HAD_ERROR';

// User Events
export const GET_USER_EVENTS_IS_PENDING = 'GET_USER_EVENTS_IS_PENDING';
export const GET_USER_EVENTS_WAS_SUCCESSFUL = 'GET_USER_EVENTS_WAS_SUCCESSFUL';
export const GET_USER_EVENTS_HAD_ERROR = 'GET_USER_EVENTS_HAD_ERROR';
export const GET_MORE_USER_EVENTS = 'GET_MORE_USER_EVENTS';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// Repository
export const GET_REPOSITORY_IS_PENDING = 'GET_REPOSITORY_IS_PENDING';
export const GET_REPOSITORY_WAS_SUCCESSFUL = 'GET_REPOSITORY_WAS_SUCCESSFUL';
export const GET_REPOSITORY_HAD_ERROR = 'GET_REPOSITORY_HAD_ERROR';

export const GET_REPOSITORY_CONTRIBUTORS_IS_PENDING = 'GET_REPOSITORY_CONTRIBUTORS_IS_PENDING';
export const GET_REPOSITORY_CONTRIBUTORS_WAS_SUCCESSFUL = 'GET_REPOSITORY_CONTRIBUTORS_WAS_SUCCESSFUL';
export const GET_REPOSITORY_CONTRIBUTORS_HAD_ERROR = 'GET_REPOSITORY_CONTRIBUTORS_HAD_ERROR';

export const GET_REPOSITORY_CONTENTS_IS_PENDING = 'GET_REPOSITORY_CONTENTS_IS_PENDING';
export const GET_REPOSITORY_CONTENTS_WAS_SUCCESSFUL = 'GET_REPOSITORY_CONTENTS_WAS_SUCCESSFUL';
export const GET_REPOSITORY_CONTENTS_HAD_ERROR = 'GET_REPOSITORY_CONTENTS_HAD_ERROR';

export const GET_REPOSITORY_ISSUES_IS_PENDING = 'GET_REPOSITORY_ISSUES_IS_PENDING';
export const GET_REPOSITORY_ISSUES_WAS_SUCCESSFUL = 'GET_REPOSITORY_ISSUES_WAS_SUCCESSFUL';
export const GET_REPOSITORY_ISSUES_HAD_ERROR = 'GET_REPOSITORY_ISSUES_HAD_ERROR';

export const GET_REPOSITORY_README_IS_PENDING = 'GET_REPOSITORY_README_IS_PENDING';
export const GET_REPOSITORY_README_WAS_SUCCESSFUL = 'GET_REPOSITORY_README_WAS_SUCCESSFUL';
export const GET_REPOSITORY_README_HAD_ERROR = 'GET_REPOSITORY_README_HAD_ERROR';

// Issue
export const GET_ISSUE_COMMENTS_IS_PENDING = 'GET_ISSUE_COMMENTS_IS_PENDING';
export const GET_ISSUE_COMMENTS_WAS_SUCCESSFUL = 'GET_ISSUE_COMMENTS_WAS_SUCCESSFUL';
export const GET_ISSUE_COMMENTS_HAD_ERROR = 'GET_ISSUE_COMMENTS_HAD_ERROR';

export const POST_ISSUE_COMMENT_IS_PENDING = 'POST_ISSUE_COMMENT_IS_PENDING';
export const POST_ISSUE_COMMENT_WAS_SUCCESSFUL = 'POST_ISSUE_COMMENT_WAS_SUCCESSFUL';
export const POST_ISSUE_COMMENT_HAD_ERROR = 'POST_ISSUE_COMMENT_HAD_ERROR';

export const HYDRATE_COMMENT_IS_PENDING = 'HYDRATE_COMMENT_IS_PENDING';
export const HYDRATE_COMMENT_WAS_SUCCESSFUL = 'HYDRATE_COMMENT_WAS_SUCCESSFUL';
export const HYDRATE_COMMENT_HAD_ERROR = 'HYDRATE_COMMENT_HAD_ERROR';

export const CREATE_REACTION_IS_PENDING = 'CREATE_REACTION_IS_PENDING';
export const CREATE_REACTION_WAS_SUCCESSFUL = 'CREATE_REACTION_WAS_SUCCESSFUL';
export const CREATE_REACTION_HAD_ERROR = 'CREATE_REACTION_HAD_ERROR';

export const DELETE_REACTION_IS_PENDING = 'DELETE_REACTION_IS_PENDING';
export const DELETE_REACTION_WAS_SUCCESSFUL = 'DELETE_REACTION_WAS_SUCCESSFUL';
export const DELETE_REACTION_HAD_ERROR = 'DELETE_REACTION_HAD_ERROR';

export const CHECK_USER_IS_COLLABORATOR_IS_PENDING = 'CHECK_USER_IS_COLLABORATOR_IS_PENDING';
export const CHECK_USER_IS_COLLABORATOR_IS_SUCCESSFUL = 'CHECK_USER_IS_COLLABORATOR_IS_SUCCESSFUL';
export const CHECK_USER_IS_COLLABORATOR_HAS_ERROR = 'CHECK_USER_IS_COLLABORATOR_HAS_ERROR';
