export default {
  black: '#000000',
  primarydark: '#262626',
  grey: '#bbb',
  greyDarkest: '#808080',
  greyBlue: '#6a737d',
  greyDark: '#999',
  greyMid: '#d1d5da',
  greyLight: '#f1f1f1',
  greyVeryLight: '#fbfbfb',
  green: '#2cbe4e',
  red: '#ee0701',
  darkRed: '#cb2431',
  white: '#ffffff',
  transparent: 'transparent',
  codeChunkBlue: '#f8f8ff',
  codeChunkLineNumberBlue: '#f3f3ff',
  addCodeGreen: '#eaffea',
  addCodeLineNumberGreen: '#DBFFD6',
  delCodeRed: '#ffecec',
  delCodeLineNumberRed: '#ffdddd',
}
