export default {
  black: '#000000',
  primarydark: '#262626',
  grey: '#bbb',
  greyDarkest: '#808080',
  greyDark: '#999',
  greyLight: '#ededed',
  greyVeryLight: '#fbfbfb',
  green: '#2cbe4e',
  red: '#ee0701',
  white: '#ffffff',
  transparent: 'transparent',
  codeChunkBlue: '#f8f8ff',
  codeChunkLineNumberBlue: '#f3f3ff',
  addCodeGreen: '#eaffea',
  addCodeLineNumberGreen: '#DBFFD6',
  delCodeRed: '#ffecec',
  delCodeLineNumberRed: '#ffdddd',
}
